
cc_library(
  name = 'glm',
  hdrs = glob(['*.hpp']),
  deps = [
    '//libraries/glm/glm/detail',
    '//libraries/glm/glm/gtc',
    '//libraries/glm/glm/gtx',
  ],
  visibility = [
    '//visibility:public'
  ]
)
