
cc_library(
  name = 'glfw',
  srcs = [
    'src/libglfw3.a',
  ],
  hdrs = glob([
    'include/GLFW/*.h',
  ]),
  includes = [
    'include',
  ],
  visibility = [
    '//visibility:public',
  ],
)
